name: Release DuuniWebapp with Docker # Name of the workflow

# On a push to the branch named master
on:
  push:
    branches: 
      - master

# Job called build runs-on ubuntu-latest
jobs:
  heroku-deploy: 
    runs-on: ubuntu-latest
    steps:
    # Checkout to the repository (the actions don't actually need this since they use the repository context anyway)
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "myduuni" #Must be unique in Heroku
        heroku_email: "duonghailee@gmail.com"
        usedocker: true
        docker_build_args: |
          API_DUUNI
      env:
        NODE_ENV: production
        API_DUUNI: ${{ secrets.API_DUUNI }}

    # # We need to login so we can later push the image without issues. 
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1 
    #   with: 
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    # # Builds my duunitori webapp
    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: duuni_devop:latest